### ISSUE TITLE
make-maas.sh error

### ISSUE THREAD

**Issue by seffyroff** [chris-sanders/maas-lxd#3]
My LXC version is 3.0.1 which breaks your version detection.
Offending lines:
https://github.com/chris-sanders/maas-lxd/blob/16c38ae54fc399160374a04de39ce09f4eb0bab7/make-maas.sh#L13

Also:
https://github.com/chris-sanders/maas-lxd/blob/16c38ae54fc399160374a04de39ce09f4eb0bab7/make-maas.sh#L28

my results:
```console
seffyroff@maas-bionic:~$ MAJOR=$(lxc version | awk -F. '{print $1}')
seffyroff@maas-bionic:~$ MINOR=$(lxc version | awk -F. '{print $2}')
seffyroff@maas-bionic:~$ echo $MAJOR 
Client version: 3 Server version: 3
seffyroff@maas-bionic:~$ echo $MINOR 
0 0
seffyroff@maas-bionic:~$ 
```
I'm commenting out the lines locally, but this is FYI.

**Comment by davecore82** [comment]
I have the same issue. Running "lxc version" gives me:

$ lxc version
Client version: 3.6
Server version: 3.6

Also I run LXD as a snap so I had to change the unit name in the following line:

`lxc network set lxdbr0 raw.dnsmasq dhcp-boot=pxelinux.0,$CONTAINER,$IPADDRESS && systemctl restart snap.lxd.daemon.service`

And in the maas-profile file, I had to change "lxc.aa_profile = unconfined" to "lxc.apparmor.profile = unconfined".

**Comment by chris-sanders** [comment]
I haven't tried 3.X or the snap, those seem reasonable. Interested in submitting a merge to handle these?

**Comment by dmzoneill** [comment]
#4 Updates for LXC 3

Please rebase

can you invite me to https://github.com/canonicalltd ?

**Comment by chris-sanders** [comment]
Fix https://github.com/chris-sanders/maas-lxd/pull/4
